const CANVAS_WIDTH = 800;
const CANVAS_HEIGHT = 600;

module.exports = {
  GAME_SETTINGS: {
    CANVAS_WIDTH,
    CANVAS_HEIGHT,
    PIPE_VELOCITY: 200,
  },
  PLAYER_PROPERTIES: {
    FLAP_VELOCITY: 300,
    MOVEMENT_VELOCITY: 200,
    STARTING_POSITION_X: CANVAS_WIDTH/10,
    STARTING_POSITION_Y: CANVAS_HEIGHT/2,
    GRAVITY_Y: 600,
  },
  PIPE_PROPERTIES: {
    PIPE_VERTICAL_DISTANCE_RANGE: [150, 250],
    PIPE_HORIZONTAL_DISTANCE_RANGE: [400, 500],
    NUMBER_OF_PIPES_TO_RENDER: 4,
  },
  STORAGE_KEYS: {
    BEST_SCORE: 'BEST_SCORE',
  }
}